packages:
  - "apps/*"
  - "packages/*"

autoInstallPeers: false

overrides:
  react: "19.3.0"
  react-dom: "19.3.0"

allowBuilds:
  "@google/genai": true
  esbuild: true
  protobufjs: true
  workerd: true

minimumReleaseAge: 1440
