/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DotwellKnownApiCatalogRouteImport } from './routes/[.]well-known/api-catalog'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiOpenapiDotjsonRouteImport } from './routes/api/openapi[.]json'
import { Route as ApiTagsRouteImport } from './routes/api/tags'
import { Route as ArticlesIdRouteImport } from './routes/articles/$id'
import { Route as ArticlesNewRouteImport } from './routes/articles/new'
import { Route as ApiArticlesIndexRouteImport } from './routes/api/articles/index'
import { Route as ApiArticlesIdRouteImport } from './routes/api/articles/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiSettingsApiKeyRouteImport } from './routes/api/settings/api-key'
import { Route as ArticlesIdOpengraphImageRouteImport } from './routes/articles/$id_/opengraph-image'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownApiCatalogRoute = DotwellKnownApiCatalogRouteImport.update({
  id: '/.well-known/api-catalog',
  path: '/.well-known/api-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiDotjsonRoute = ApiOpenapiDotjsonRouteImport.update({
  id: '/api/openapi.json',
  path: '/api/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTagsRoute = ApiTagsRouteImport.update({
  id: '/api/tags',
  path: '/api/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIdRoute = ArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesNewRoute = ArticlesNewRouteImport.update({
  id: '/articles/new',
  path: '/articles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArticlesIndexRoute = ApiArticlesIndexRouteImport.update({
  id: '/api/articles/',
  path: '/api/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArticlesIdRoute = ApiArticlesIdRouteImport.update({
  id: '/api/articles/$id',
  path: '/api/articles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsApiKeyRoute = ApiSettingsApiKeyRouteImport.update({
  id: '/api/settings/api-key',
  path: '/api/settings/api-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIdOpengraphImageRoute =
  ArticlesIdOpengraphImageRouteImport.update({
    id: '/articles/$id_/opengraph-image',
    path: '/articles/$id/opengraph-image',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/tags': typeof ApiTagsRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/articles/new': typeof ArticlesNewRoute
  '/api/articles/$id': typeof ApiArticlesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/settings/api-key': typeof ApiSettingsApiKeyRoute
  '/articles/$id/opengraph-image': typeof ArticlesIdOpengraphImageRoute
  '/api/articles/': typeof ApiArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/tags': typeof ApiTagsRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/articles/new': typeof ArticlesNewRoute
  '/api/articles/$id': typeof ApiArticlesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/settings/api-key': typeof ApiSettingsApiKeyRoute
  '/articles/$id/opengraph-image': typeof ArticlesIdOpengraphImageRoute
  '/api/articles': typeof ApiArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/tags': typeof ApiTagsRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/articles/new': typeof ArticlesNewRoute
  '/api/articles/$id': typeof ApiArticlesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/settings/api-key': typeof ApiSettingsApiKeyRoute
  '/articles/$id_/opengraph-image': typeof ArticlesIdOpengraphImageRoute
  '/api/articles/': typeof ApiArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/llms.txt'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/.well-known/api-catalog'
    | '/api/mcp'
    | '/api/openapi.json'
    | '/api/tags'
    | '/articles/$id'
    | '/articles/new'
    | '/api/articles/$id'
    | '/api/auth/$'
    | '/api/settings/api-key'
    | '/articles/$id/opengraph-image'
    | '/api/articles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/llms.txt'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/.well-known/api-catalog'
    | '/api/mcp'
    | '/api/openapi.json'
    | '/api/tags'
    | '/articles/$id'
    | '/articles/new'
    | '/api/articles/$id'
    | '/api/auth/$'
    | '/api/settings/api-key'
    | '/articles/$id/opengraph-image'
    | '/api/articles'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/llms.txt'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/.well-known/api-catalog'
    | '/api/mcp'
    | '/api/openapi.json'
    | '/api/tags'
    | '/articles/$id'
    | '/articles/new'
    | '/api/articles/$id'
    | '/api/auth/$'
    | '/api/settings/api-key'
    | '/articles/$id_/opengraph-image'
    | '/api/articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DotwellKnownApiCatalogRoute: typeof DotwellKnownApiCatalogRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiOpenapiDotjsonRoute: typeof ApiOpenapiDotjsonRoute
  ApiTagsRoute: typeof ApiTagsRoute
  ArticlesIdRoute: typeof ArticlesIdRoute
  ArticlesNewRoute: typeof ArticlesNewRoute
  ApiArticlesIdRoute: typeof ApiArticlesIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSettingsApiKeyRoute: typeof ApiSettingsApiKeyRoute
  ArticlesIdOpengraphImageRoute: typeof ArticlesIdOpengraphImageRoute
  ApiArticlesIndexRoute: typeof ApiArticlesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/api-catalog': {
      id: '/.well-known/api-catalog'
      path: '/.well-known/api-catalog'
      fullPath: '/.well-known/api-catalog'
      preLoaderRoute: typeof DotwellKnownApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi.json': {
      id: '/api/openapi.json'
      path: '/api/openapi.json'
      fullPath: '/api/openapi.json'
      preLoaderRoute: typeof ApiOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tags': {
      id: '/api/tags'
      path: '/api/tags'
      fullPath: '/api/tags'
      preLoaderRoute: typeof ApiTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$id': {
      id: '/articles/$id'
      path: '/articles/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof ArticlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/new': {
      id: '/articles/new'
      path: '/articles/new'
      fullPath: '/articles/new'
      preLoaderRoute: typeof ArticlesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/articles/': {
      id: '/api/articles/'
      path: '/api/articles'
      fullPath: '/api/articles/'
      preLoaderRoute: typeof ApiArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/articles/$id': {
      id: '/api/articles/$id'
      path: '/api/articles/$id'
      fullPath: '/api/articles/$id'
      preLoaderRoute: typeof ApiArticlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/api-key': {
      id: '/api/settings/api-key'
      path: '/api/settings/api-key'
      fullPath: '/api/settings/api-key'
      preLoaderRoute: typeof ApiSettingsApiKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$id_/opengraph-image': {
      id: '/articles/$id_/opengraph-image'
      path: '/articles/$id/opengraph-image'
      fullPath: '/articles/$id/opengraph-image'
      preLoaderRoute: typeof ArticlesIdOpengraphImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DotwellKnownApiCatalogRoute: DotwellKnownApiCatalogRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiOpenapiDotjsonRoute: ApiOpenapiDotjsonRoute,
  ApiTagsRoute: ApiTagsRoute,
  ArticlesIdRoute: ArticlesIdRoute,
  ArticlesNewRoute: ArticlesNewRoute,
  ApiArticlesIdRoute: ApiArticlesIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSettingsApiKeyRoute: ApiSettingsApiKeyRoute,
  ArticlesIdOpengraphImageRoute: ArticlesIdOpengraphImageRoute,
  ApiArticlesIndexRoute: ApiArticlesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
