import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

type Usage = "runtime" | "referenceOnly" | "testOracle";

type LockedFile = {
  path: string;
  sha256: string;
  usage: Usage;
};

type LockedSource = {
  id: string;
  repository: string;
  commit: string;
  license: string;
  files: LockedFile[];
};

type SourceLock = {
  version: 1;
  sources: LockedSource[];
};

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function parseFile(value: unknown): LockedFile {
  if (
    !isRecord(value) ||
    typeof value.path !== "string" ||
    typeof value.sha256 !== "string" ||
    (value.usage !== "runtime" && value.usage !== "referenceOnly" && value.usage !== "testOracle")
  ) {
    throw new Error("Invalid locked skill file");
  }
  return { path: value.path, sha256: value.sha256, usage: value.usage };
}

function parseSource(value: unknown): LockedSource {
  if (
    !isRecord(value) ||
    typeof value.id !== "string" ||
    typeof value.repository !== "string" ||
    typeof value.commit !== "string" ||
    typeof value.license !== "string" ||
    !Array.isArray(value.files)
  ) {
    throw new Error("Invalid locked skill source");
  }
  return {
    id: value.id,
    repository: value.repository,
    commit: value.commit,
    license: value.license,
    files: value.files.map(parseFile),
  };
}

function parseLock(value: unknown): SourceLock {
  if (!isRecord(value) || value.version !== 1 || !Array.isArray(value.sources)) {
    throw new Error("Unsupported skill source lock");
  }
  return { version: 1, sources: value.sources.map(parseSource) };
}

function rawUrl(source: LockedSource, file: LockedFile): string {
  const match = /^https:\/\/github\.com\/([^/]+)\/([^/]+?)(?:\.git)?$/u.exec(source.repository);
  if (!match?.[1] || !match[2]) throw new Error(`Unsupported repository URL: ${source.repository}`);
  return `https://raw.githubusercontent.com/${match[1]}/${match[2]}/${source.commit}/${file.path}`;
}

async function download(source: LockedSource, file: LockedFile): Promise<string> {
  const response = await fetch(rawUrl(source, file));
  if (!response.ok)
    throw new Error(`Failed to download ${source.id}/${file.path}: ${response.status}`);

  const content = await response.text();
  const hash = createHash("sha256").update(content).digest("hex");
  if (hash !== file.sha256) throw new Error(`Hash mismatch for ${source.id}/${file.path}`);
  return content;
}

async function main(): Promise<void> {
  const lockPath = resolve(packageRoot, "sources.lock.json");
  const parsedLock: unknown = JSON.parse(await readFile(lockPath, "utf8"));
  const lock = parseLock(parsedLock);
  const runtime = new Map<string, string[]>();

  for (const source of lock.sources) {
    for (const file of source.files) {
      const content = await download(source, file);
      if (file.usage === "runtime") {
        const entries = runtime.get(source.id);
        if (entries) {
          entries.push(content.trim());
          continue;
        }
        const firstEntry = [content.trim()];
        runtime.set(source.id, firstEntry);
      }
    }
  }

  const registrySource = `// Generated by pnpm skills:sync. Do not edit.\nexport const generatedSkills = ${JSON.stringify(
    Object.fromEntries([...runtime].map(([id, files]) => [id, files.join("\n\n")])),
    null,
    2,
  )} satisfies Readonly<Record<string, string>>;\n`;
  const notice = [
    "# Third-party skill attribution",
    "",
    "Generated from `sources.lock.json`. Only entries marked `runtime` are bundled.",
    "",
    ...lock.sources.flatMap((source) => [
      `## ${source.id}`,
      "",
      `- Source: ${source.repository}`,
      `- Commit: \`${source.commit}\``,
      `- Declared license: ${source.license}`,
      `- Usage: ${[...new Set(source.files.map((file) => file.usage))].join(", ")}`,
      "",
    ]),
  ].join("\n");

  const generatedPath = resolve(packageRoot, "src/generated/registry.ts");
  await mkdir(dirname(generatedPath), { recursive: true });
  await writeFile(generatedPath, registrySource, "utf8");
  await writeFile(resolve(packageRoot, "THIRD_PARTY_NOTICES.md"), `${notice}\n`, "utf8");
}

await main();
